### ISSUE TITLE
How do you discover mega buffed minions?

### ISSUE THREAD

**Issue by jeremysalwen** [JDBumgardner/stone_ground_hearth_battles#23]
I saw this on reddit: https://www.reddit.com/r/BobsTavern/comments/izfia4/hmmm_tough_choice/

How do you get a discover choice of a mega buffed minion like that?

**Comment by JDBumgardner** [comment]
Do cards go back with buffs?

**Comment by ethansaxenian** [comment]
That is Mr. Bigglesworth's hero power, which lets you discover a _buffed_ minion from an opponent's board when they die.

**Comment by jeremysalwen** [comment]
Oh cool.
