### ISSUE TITLE
Selling AlleyCat makes you have 10 coins??

### ISSUE THREAD

**Issue by jeremysalwen** [JDBumgardner/stone_ground_hearth_battles#29]
I saw the bot do this during training.  It seems to gain 10 coins when selling alley cat.  Do we have any idea how this could happen?

![image](https://user-images.githubusercontent.com/450638/95151412-9dbf2b80-0758-11eb-8382-ced6ae49f3c5.png)

**Comment by JDBumgardner** [comment]
We should record the learning bot's hero.

**Comment by ethansaxenian** [comment]
Do we know what else was on the board?

**Comment by JDBumgardner** [comment]
Has it just got to the action limit there and that's actually a turn end?

**Comment by JDBumgardner** [comment]
Winner^^. For _ in range(20) in host 55 - 35 = 20.

**Comment by ethansaxenian** [comment]
Nice catch! We definitely need to increase the action limit.
