### ISSUE TITLE
Mr Bigglesworth Discover when an opponent commits suicide with a vulgar homonculus?

### ISSUE THREAD

**Issue by jeremysalwen** [JDBumgardner/stone_ground_hearth_battles#52]
We encountered a bug where another player dying on their turn causes Mr Bigglesworth to be forced to discover a card in the middle of their turn.  This breaks our simulator because it causes a valid action to become invalid (until the user chooses the card to discover).

What is the actual OG behavior?

**Comment by jazzcs** [comment]
All Bigglesworth discovers occur on the beginning of the next turn. They discover M times if M heroes died the previous turn. Is this what you're asking?

**Comment by jeremysalwen** [comment]
Yes. Thanks! We have implemented it this way now.
