### ISSUE TITLE
BrannBronzeBeard target selection

### ISSUE THREAD

**Issue by jeremysalwen** [JDBumgardner/stone_ground_hearth_battles#53]
Our current implementation triggers battlecries N times on the same targets when brann bronzebeard is active.   Should you instead be able to select targets N times?

**Comment by jazzcs** [comment]
If it's targeted, then it's N times on the same target. If non targeted,  N
random valid targets.

**Comment by jeremysalwen** [comment]
Ok great, this is already what we have!
